name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x
    - name: Variable Substitution appsettings file for tests
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/DependabotSecretsPOC.Tests/appsettings.json'
      env:
        AppSettings.MySecret: "${{ secrets.MYSECRET }}"   
    - name: Test
      run: dotnet test src/DependabotSecretsPOC.sln
